### ISSUE TITLE
Timeout when adding a new user to a tenant

### ISSUE THREAD

**Issue by Alevsk** [minio/m3#113]
When trying to add a new user to a tenant via:

```
./m3 tenant user add --tenant TENANT --email email@domain.com --name somename --password somepassword
```
We are getting this error after a timeout:
```
Error adding user: Put http://XXXXXX-sg-1:9001/minio/admin/v1/add-user?accessKey=XXXXXXXX: dial tcp: lookup XXXXXX-sg-1: no such host
```
However the user is created correctly

**Comment by dvaldivia** [comment]
When the users gets created we create some UI credentials for him and try to send them over the the tenant's minio instance, the problem here is that during development the individual tenant instance needs to be port-forwarded.

We also have the problem of controlling the timeout, there's a 1 minute timeout on `madmin` but we cannot influence it, so we would need to start the change from MinIO repo

**Comment by dvaldivia** [comment]
Is this still happening with the pre-provisioning approach?
